# Generated by Django 5.0.3 on 2024-04-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='Comments',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='DeviceType',
            field=models.CharField(default='DeviceType', max_length=100),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='OnOffSite',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
