# Generated by Django 5.0.3 on 2024-04-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0002_alter_hardware_comments_alter_hardware_devicetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronic_hardware',
            name='DeviceType',
            field=models.CharField(default='DeviceType', max_length=100, null=True),
        ),
    ]
