# Generated by Django 5.0.3 on 2024-04-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0003_electronic_hardware_devicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronic_hardware',
            name='DeviceName',
            field=models.CharField(default='DeviceName', max_length=200, null=True),
        ),
    ]
