# Generated by Django 5.0.4 on 2024-04-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0005_alter_electronic_hardware_devicename'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronic_hardware',
            name='Quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='electronic_hardware',
            name='Status',
            field=models.CharField(default='Status', max_length=100, null=True),
        ),
    ]
