# Generated by Django 5.0.3 on 2024-04-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0006_electronic_hardware_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire_reference',
            name='Status',
            field=models.CharField(default='Status', max_length=100),
        ),
    ]
