# Generated by Django 5.0.4 on 2024-04-30 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0007_hire_reference_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hire_reference',
            old_name='AdminID',
            new_name='AdminUsername',
        ),
        migrations.RenameField(
            model_name='hire_reference',
            old_name='UserID',
            new_name='Username',
        ),
        migrations.RemoveField(
            model_name='hire_reference',
            name='Cost',
        ),
    ]
