# Generated by Django 5.0.4 on 2024-04-30 22:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0008_rename_adminid_hire_reference_adminusername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire_reference',
            name='Hire_EndDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hire_reference',
            name='Hire_StartDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
