# Generated by Django 5.0.4 on 2024-05-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0009_alter_hire_reference_hire_enddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hire_reference',
            old_name='AdminUsername',
            new_name='DeviceName',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='RefID',
        ),
        migrations.RemoveField(
            model_name='hire_reference',
            name='RefID',
        ),
    ]
