# Generated by Django 5.0.4 on 2024-05-01 16:29

import InventorySystem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0010_rename_adminusername_hire_reference_devicename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire_reference',
            name='Hire_EndDate',
            field=models.DateField(default=InventorySystem.models.default_hire_end_date),
        ),
    ]
