# Generated by Django 5.0.4 on 2024-05-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0011_alter_hire_reference_hire_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire_reference',
            name='Status',
            field=models.CharField(default='Booked', max_length=100),
        ),
    ]
