# Generated by Django 5.0.4 on 2024-05-01 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0012_alter_hire_reference_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire_reference',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventorySystem.user'),
        ),
    ]
